AWSTemplateFormatVersion: '2010-09-09'
Description: Create a RDS DB Security Group.
Parameters:
  SecurityGroupName:
    Description: The name of the Security Group Name tag.
    Type: String
  VpcID:
    Description: VPC ID of the Database
    Type: AWS::EC2::VPC::Id
  ServiceTag:
    Description: Value of the tag Service
    Type: String
    Default: staging
    AllowedValues:
      - production
      - staging
    ConstraintDescription: must be a predefined tag.
  EC2CIDR:
    Description: IP Address range of a EC2 allowed connecting to the RDS.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      EC2VpcId: !Ref 'VpcID'
      GroupDescription: !Ref 'SecurityGroupName'
      DBSecurityGroupIngress:
        - EC2SecurityGroupId: !Ref 'SecurityGroup'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackName'
        - Key: Name
          Value: !Ref 'SecurityGroupName'
        - Key: Service
          Value: !Ref 'ServiceTag'
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref 'VpcID'
      GroupDescription: !Ref 'SecurityGroupName'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref 'EC2CIDR'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackName'
        - Key: Name
          Value: !Ref 'SecurityGroupName'
        - Key: Service
          Value: !Ref 'ServiceTag'
